# Generated by Django 5.1.3 on 2024-12-18 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the payment method (e.g., bKash, Nagad, Credit Card)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the payment method', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if this payment method is currently active')),
                ('requires_mobile_number', models.BooleanField(default=False, help_text='Does this method require a mobile number? (e.g., bKash, Nagad)')),
                ('requires_transaction_id', models.BooleanField(default=True, help_text='Does this method require a transaction ID?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The payment amount', max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Pending', help_text='Current status of the payment', max_length=10)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID provided by the payment gateway', max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, help_text='Mobile number used for payment, if applicable', max_length=15, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payment.paymentmethod')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_response', models.JSONField(blank=True, help_text='Response from the payment gateway', null=True)),
                ('success', models.BooleanField(default=False, help_text='Whether the transaction was successful')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='payment.payment')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
