# Generated by Django 5.1.3 on 2024-12-30 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_patient_latitude_patient_location_patient_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Collected', 'Collected'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('collection_time', models.DateTimeField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('result_sent', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testtype')),
            ],
        ),
        migrations.CreateModel(
            name='TestCollectionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Assigned', max_length=50)),
                ('collection_date', models.DateTimeField(blank=True, null=True)),
                ('hospital_team_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.hospitalteam')),
                ('test_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testorder')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('result_date', models.DateTimeField(auto_now_add=True)),
                ('result_sent', models.BooleanField(default=False)),
                ('test_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tests.testorder')),
            ],
        ),
    ]
