# Generated by Django 5.1.3 on 2024-12-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_testorder_latitude_testorder_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testorder',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
    ]
