# Generated by Django 5.1.3 on 2024-12-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_testorder_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='testorder',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
