# Generated by Django 5.1.3 on 2025-01-01 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_testorder_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='testorder',
            name='email',
        ),
        migrations.RemoveField(
            model_name='testorder',
            name='name',
        ),
        migrations.RemoveField(
            model_name='testorder',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='testresult',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='test_results/'),
        ),
        migrations.AlterField(
            model_name='testorder',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('sample_collected', 'Sample Collected'), ('in_analysis', 'In Analysis'), ('completed', 'Completed'), ('result_delivered', 'Result Delivered')], default='requested', max_length=50),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('collector', 'Sample Collector'), ('technician', 'Lab Technician')], max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
