# Generated by Django 5.1.3 on 2025-01-01 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_alter_testorder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcollectionassignment',
            name='hospital_team_member',
        ),
        migrations.DeleteModel(
            name='HospitalTeam',
        ),
    ]
