# Generated by Django 5.1.3 on 2025-01-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_remove_testcollectionassignment_hospital_team_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
