# Generated by Django 5.1.3 on 2025-03-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_alter_testresult_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='testorder',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
