# Generated by Django 5.1.3 on 2025-03-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_testorder_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='testorder',
            name='total_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
