# Generated by Django 5.1.3 on 2025-03-06 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_remove_testtype_price_testtype_estimate_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testtype',
            old_name='description',
            new_name='details',
        ),
    ]
