# Generated by Django 5.1.3 on 2024-12-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_patient_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='video_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
