# Generated by Django 5.1.3 on 2024-12-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_prescription_next_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_problem',
            field=models.TextField(blank=True, help_text="Description of the patient's current problem or symptoms", null=True),
        ),
    ]
