# Generated by Django 5.1.3 on 2025-03-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_appointment_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('services', models.TextField(blank=True, help_text='Comma-separated list of services')),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('about_service', models.TextField(blank=True, help_text='Details about the service provided')),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='consultation_fee',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialty',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialties',
            field=models.ManyToManyField(related_name='doctors', to='hospital.specialty'),
        ),
    ]
