# Generated by Django 5.1.3 on 2025-03-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_remove_doctor_specialties_specialty_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='nid_number',
            field=models.CharField(blank='True', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_profiles/'),
        ),
    ]
