# Generated by Django 5.1.3 on 2025-03-23 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_reportcategory_remove_patientreport_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_test_types', to='patients.reportcategory')),
            ],
        ),
        migrations.AlterField(
            model_name='patientreport',
            name='test_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_reports', to='patients.patienttesttype'),
        ),
        migrations.DeleteModel(
            name='TestType',
        ),
    ]
