# Generated by Django 5.1.3 on 2025-03-25 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patienttesttype_alter_patientreport_test_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientTestType',
            new_name='ReportType',
        ),
    ]
