# Generated by Django 5.1.3 on 2025-03-25 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_rename_patienttesttype_reporttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientreport',
            name='test_type',
        ),
        migrations.AddField(
            model_name='patientreport',
            name='report_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_type', to='patients.reporttype'),
        ),
    ]
