# Generated by Django 5.1.3 on 2025-03-25 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_remove_patientreport_test_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreport',
            name='report_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_reports', to='patients.reporttype'),
        ),
    ]
